from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetCompleteView, \
    PasswordResetDoneView
from django.urls import path, path, include

from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.conf.urls.i18n import i18n_patterns

from . import views
from .views import FriendSearchResultsView

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.BackgroundView.as_view(), name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signout/', views.signout, name='signout'),
    path('mythemes/', views.background_theme_create, name='mythemes'),
    path('create_community/', views.CreateCommunityView.as_view(), name='create_community'),
    path('mycommunities/', views.MyCommunityView.as_view(), name='mycommunities'),
    path('friendslist/', views.FriendView.as_view(), name='friendslist'),
    path('friendslist_results/', views.FriendView.as_view(), name='friendslistresults'),
    path('friend-search/', FriendSearchResultsView.as_view(), name='friend-search'),
    path('friendslist/search/', views.FriendSearchResultsView.as_view(), name='friend_search'),
    path('nav/', TemplateView.as_view(template_name='nav.html'), name='nav'),
    path('base/', TemplateView.as_view(template_name='base.html'), name='base'),
    path('set-current-theme/<int:pk>/', views.set_current_theme, name='set-current-theme'),
    path('themelist/', views.BackgroundThemeListView.as_view(), name='themelist'),
    path('signup_success/', views.signup_success, name='signup_success'),
    path('profile/<str:username>/', views.ProfileView.as_view(), name='profile'),
    path('profile/<str:username>/edit/', views.ProfileSettingsView.as_view(), name='profile_settings'),
    path('account_settings/', views.SettingsView.as_view(), name='account_settings'),
    path('profile/<str:username>/followers/', views.followers, name='followers'),
    path('profile/<str:username>/following/', views.following, name='following'),
    path('post/<int:pk>/', views.PostsView.as_view(), name='post'),
    path('post/<int:post_id>/comment_count/', views.get_comment_count, name='comment_count'),
    path('post/', views.post_picture, name='post_picture'),
    path('explore/', views.ExploreView.as_view(), name='explore'),
    path('scrollexplore/', views.ScrollExploreView.as_view(), name='scrollexplore'),
    path('discover/', views.DiscoverCommunityView.as_view(), name='discover'),
    path('scrolldiscover/', views.ScrollDiscoverView.as_view(), name='scrolldiscover'),
    path('notifications/', views.notifications, name='notifications'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/<str:label>/', views.chat, name='chat'),
    path('new_chat/', views.ChatView.as_view(), name='new_chat'),
    path('user.username/<str:room>/', views.room, name='room'),
    path('new_chat/<str:room>/', views.RoomView.as_view(), name='room'),
    path('new_chat/checkview', views.checkview, name='checkview'),
    path('new_chat/send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
    path('getDirectMessages/<str:room>/', views.getDirectMessages, name='getDirectMessages'),
    path('send_post_to_friend/<int:post_id>/<str:room_name>/', views.send_post_to_friend, name='send_post_to_friend'),
    path('events/', views.ListView.as_view(), name="events"),
    path('list/<int:list_id>/', views.ItemListView.as_view(), name="list"),
    path('list/add/', views.ListCreate.as_view(), name="list-add"),
    path('list/<int:pk>/delete/', views.ListDelete.as_view(), name="list-delete"),
    path('list/<int:list_id>/item/add/', views.ItemCreate.as_view(), name="item-add"),
    path('list/<int:list_id>/item/<int:pk>/', views.ItemUpdate.as_view(), name="item-update"),
    path('list/<int:list_id>/item/<int:pk>/delete/', views.ItemDelete.as_view(), name="item-delete"),
    path('post/<int:pk>/likes/', views.likes, name='likes'),
    path('like/', views.add_like, name='like'),
    path('comment/', views.add_comment, name='comment'),
    path('follow_toggle/', views.follow_toggle, name='follow_toggle'),
    path('reset_password/', PasswordResetView.as_view(), name='reset_password'),
    path('reset-password/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset_password/confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset-password/complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='commons/password-reset/password_reset.html',
                                              subject_template_name='commons/password-reset/password_reset_subject.txt',
                                              email_template_name='commons/password-reset/password_reset_email.html',
                                              success_url='/login/'),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='commons/password-reset/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='commons/password-reset/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='commons/password-reset/password_reset_complete.html'),
         name='password_reset_complete'),
]
